
let answers = {
  " Fainted": "Check if they are breathing, if not begin CPR, if they are breathing then put them in the recovery position",
  " Recovery Position": "Kneel by the casualty and straighten their legs.If they are wearing glasses, or have any bulky items in their pockets, remove them.  Do not search their pockets for small items. Place the arm that is nearest to you at a right angle to their body, with the elbow bent and their palm facing upwards.Bring their other arm across their chest and place the back of their hand against the cheek nearest to you. Hold it there. With your other hand, pull their far knee up so that their foot is flat on the floor.  Keeping the back of the casualty’s hand pressed against their cheek, pull on the far leg to roll the casualty towards you on to their side. You can then adjust the top leg so that it is bent at a right angle.Gently tilt the casualty’s head back and lift their chin to make sure their airway stays open. You can adjust the hand under their cheek to do this.",
  "CPR" : "Hands-only CPR To carry out a chest compression Kneel next to the person and place the heel of your hand on the breastbone at the centre of their chest. Place the palm of your other hand on top of the hand that's on their chest and interlock your fingers.  Position yourself so your shoulders are directly above your hands.Using your body weight (not just your arms), press straight down by 5 to 6cm (2 to 2.5 inches) on their chest.Keeping your hands on their chest, release the compression and allow their chest to return to its original position   Repeat these compressions at a rate of 100 to 120 times a minute until an ambulance arrives or for as long as you can. For CPR with rescue breaths   Place the heel of your hand on the centre of the persons chest, then place the palm of your other hand on top and press down by 5 to 6cm (2 to 2.5 inches) at a steady rate of 100 to 120 compressions a minute.After every 30 chest compressions, give 2 rescue breaths.   Tilt the person's head gently and lift the chin up with 2 fingers. Pinch the person's nose. Seal your mouth over their mouth and blow steadily and firmly into their mouth for about 1 second. Check that their chest rises. Give 2 rescue breaths. Continue with cycles of 30 chest compressions and 2 rescue breaths until they begin to recover or emergency help arrives.",
  "burn": "If someone has a burn or scald: Cool the burn as quickly as possible with cool running water for at least 20 minutes, or until the pain is relieved.  Call 112 or seek medical help, if needed.   While cooling the burn, and before the area begins to swell, carefully remove any clothing or jewellery, unless it's attached to the skin.  If you're cooling a large burnt area, particularly in babies, children and elderly people, be aware that it may cause hypothermia (it may be necessary to stop cooling the burn to avoid hypothermia).  If the burn has cooled, cover it loosely with cling film. If cling film isn't available, use a clean, dry dressing or non-fluffy material. Do not wrap the burn tightly as swelling may lead to further injury. Do not apply creams, lotions or sprays to the burn.",
  "stroke": "If someone has a stroke: Call 911 immediately,Note the time you first see symptoms Perform CPR, if necessary if your friend or spouse is unconscious when you find them, check their pulse and breathing. If you find none, call 911 and start CPR while you’re waiting for the ambulance to arrive.  Do not let that person go to sleep or talk you out of calling 911  Do not give them medication, food, or drinks  Do not drive yourself or someone else to the emergency room,    Stay Focused and Take Action Quickly",
  "choking":" Child and adult If a choking person can cough forcefully, let the person keep coughing. Coughing might naturally remove the stuck object. If a person can't cough, talk, cry or laugh forcefully, give first aid to the person.  Give five back blows. Stand to the side and just behind a choking adult. \n For a child, kneel down behind. Place your arm across the person's chest to support the person's body. Bend the person over at the waist to face the ground. Strike five separate times between the person's shoulder blades with the heel of your hand Give five abdominal thrusts. If back blows don't remove the stuck object, give five abdominal thrusts, also known as the Heimlich maneuver.  Alternate between five blows and five thrusts until the blockage is dislodged.To give abdominal thrusts to someone else:Stand behind the person. For a child, kneel down behind. Place one foot slightly in front of the other for balance. Wrap your arms around the waist. Tip the person forward slightly.  Make a fist with one hand. Put it just above the person's navel.   Grasp the fist with the other hand. Press into the stomach, also called the abdomen, with a quick, upward thrust — as if trying to lift the person up. For a child, use gentle yet firm pressure to avoid damaging the internal organs.   Give five abdominal thrusts. Check if the blockage has been removed. Repeat as needed.  If you're the only rescuer, give back blows and abdominal thrusts first. Then call 911 or your local emergency number for help. If another person is there, have that person call for help while you give first aid. If the person becomes unconscious, start standard cardiopulmonary resuscitation (CPR) with chest compressions and rescue breaths.  To clear the airway of an unconscious person.  Lower the person onto the floor, with the back on the floor and arms to the sides.   Clear the airway. If you can see the object, reach a finger into the mouth to sweep out the object. Never finger sweep if you can't see the object. You risk pushing the blockage deeper into the airway. This is very risky with young children.  Begin CPR if the person still doesn't respond. If the airway is still blocked, use chest compressions such as those that are used in CPR to remove the stuck object. Only use two rescue breaths per cycle. Recheck the mouth regularly for the object. If you're alone and choking:Call 911 or your local emergency number right away. Then, give yourself abdominal thrusts, also called the Heimlich maneuver, to remove the stuck object.",
"seizure": "If you're with someone having a seizure only move them if they're in danger, such as near a busy road or hot cooker cushion their head if they're on the ground loosen any tight clothing around their neck, such as a collar or tie, to aid breathing turn them on to their side after their convulsions stop – recovery position stay with them and talk to them calmly until they recover note the time the seizure starts and finishes If the person is in a wheelchair, put the brakes on and leave any seatbelt or harness on. Support them gently and cushion their head, but do not try to move them. Do not put anything in their mouth, including your fingers. They should not have any food or drink until they have fully recovered.  When to call an ambulance Call 999 and ask for an ambulance if it's the first time someone has had a seizure  the seizure lasts longer than is usual for them the seizure lasts more than 5 minutes, if you do not know how long their seizures usually last  the person does not regain full consciousness, or has several seizures without regaining consciousness the person is seriously injured during the seizure the person has difficulty breathing after the seizure People with epilepsy do not always need an ambulance or to go to hospital every time they have a seizure.",
  "sting":"The first thing you need to do is remove the stinger, if it is left in or on your skin.If there's nothing on or in your skin, or you've removed what was on your skin, wash the affected area with soap and water. This will help lower the chance of infection.Ask your pharmacist about medicines that can help ease the symptoms of a sting, such as  antihistamines - these are commonly used, but do not always work wellsteroid creams painkillers, such as ibuprofen or paracetamol - do not give aspirin to children under age 16 If the insect bite or sting is not serious, there are other things you can do at home to ease your symptoms. put a cold compress on the bite or sting for at least 20 minutes if it's swollen keep the area raised to reduce swelling, for a jellyfish sting, type (Jellyfish (do not include the word sting)) into the question box",
  "jellyfish":"Most jellyfish stings are harmless. But some jellyfish stings can cause serious harm. If you or someone you’re with is stung, get help right away. If you’re experiencing life-threatening symptoms such as difficulty breathing, call 911 or go to your nearest emergency room.Most people don’t need to see their healthcare provider for a jellyfish sting. Depending on the type of jellyfish, you can administer first aid for most stings. You can treat mild jellyfish stings using the following steps:Wash the tentacles and venom off the affected area of your body with seawater. Don’t use freshwater. Using tweezers or gloved hands, remove any tentacles you see in your skin.  Apply vinegar or rubbing alcohol to the affected area to stop any more firings of nematocysts. (You shouldn’t use vinegar for Portuguese man-of-war stings, though. It can cause more venom to be released from the nematocysts.)  To help reduce the pain, you can put calamine lotion or hydrocortisone cream on a jellyfish sting. You can also use an ice pack or hot water to help with the pain and swelling.",
"concussion" :"Seek medical attention immediately after a concussion if you or someone you know has these symptoms.If you or someone you know has concussion symptoms that last more than two weeks, consider seeing a doctor ",
  "broken":"if a bone is broken seek immediate medical attention. If you are out somewhere with no way of contacting help, try to create a temporary solution such as a sling or a splint using your first aid kit. If you cannot do this or are on your own , send out an emergency signal such as a flare or call for help.",
  "stab": "If someone is stabbed, seek immediate medical help (911). If the knife is still in there head, DO NOT remove it.Immediately apply pressure around the object in order to try and stop the bleeding and continue this until emergency services arrive.If you suspect someone is going into shock:continue to apply pressure to the wound to stop the blood coming out call 999 if you haven't already done solie them down and lift their feet higher than the rest of their body. This keeps their legs higher than their heart, which helps increase blood flow to their brain and heart reassure them and wrap them in coats or a blanket to keep them warm.",
  "splinter":"To remove a splinter: Wash your hands, then the area around the splinter with soap and warm water  Check out the splinter carefully. You might need a magnifying glass to see it if it's very small. Sterilize tweezers and a needle with rubbing alcohol. If you don’t have rubbing alcohol, you can put the ends of each in boiling water, then wipe them off with a clean cotton ball or pad. If the splinter is sticking through the skin, firmly grip the end with the tweezers. Pull slowly and gently at the same angle the splinter went in so it won't break. If the tip of the splinter isn't sticking out, gently use the needle to poke the end of the splinter. Then push the splinter out until you can grab the end with the tweezers. Sometimes you might need to gently scrape away the skin that’s over the splinter until you can grab the end.Check to be sure all pieces of the splinter came out. Then, wash the area with soap and warm water once more"
};
function askQuestion() {
  let question = document.getElementById("userQuestion").value; 

  let lowercaseAnswers = {};
  for (const key in answers) {
    lowercaseAnswers[key.toLowerCase()] = answers[key]; 
  }

  let foundAnswer = false;
  for (const keyword in lowercaseAnswers) {
    if (question.toLowerCase().includes(keyword)) {
      document.getElementById("answer").innerHTML = lowercaseAnswers[keyword];
      foundAnswer = true;
      break; // Stop searching after finding a match
    }
  }

  if (!foundAnswer) {
    document.getElementById("answer").innerHTML = "I don't know the answer to that.Please either get emergency help or try a different keyword"; 
     }
  { var num = document.getElementById("answer");
  num.style.fontSize = "20px";
   num.style.color="darkred";
  }
}